//{id}&&{Type}&&{name}&&{details}
//detail複数行 = ${line1}${line2}${line3}...
var item_data = [
  "0&&Other&&no item",
  "1&&Erina&&Piko Hammer",
  "2&&Erina&&Air Jump",
  "3&&Erina&&Sliding Powder",
  "4&&Erina&&Carrot Bomb",
  "5&&Erina&&Hourglass",
  "6&&Erina&&Speed Boost",
  "7&&Ribbon&&Auto Earrings",
  "8&&Ribbon&&Ribbon&&Ribbon will join you as soon as you screen transition or save and reload",
  "9&&Erina&&Soul Heart",
  "10&&Erina&&Rabi Slippers",
  "11&&Erina&&Bunny Whirl",
  "12&&Ribbon&&Quick Barrette",
  "13&&Ribbon&&Book of Carrot",
  "14&&Ribbon&&Chaos Rod",
  "15&&Erina&&Hammer Wave",
  "16&&Erina&&Hammer Roll",
  "17&&Erina&&Light Orb",
  "18&&Erina&&Water Orb",
  "19&&Erina&&Fire Orb",
  "20&&Erina&&Nature Orb",
  "21&&Erina&&P Hairpin",
  "22&&Ribbon&&Sunny Beam",
  "23&&Ribbon&&Plus Necklace",
  "24&&Ribbon&&Cyber Flower",
  "25&&Ribbon&&Healing Staff",
  "26&&Ribbon&&Max Bracelet",
  "27&&Ribbon&&Explode Shot",
  "28&&Erina&&Air Dash",
  "29&&Erina&&Bunny Strike",
  "30&&Erina&&Strange Box",
  "31&&Erina&&Wall Jump",
  "32&&Erina&&Spike Barrier",
  "33&&Erina&&Bunny Amulet",
  "34&&Ribbon&&Charge Ring",
  "35&&Ribbon&&Carrot Shooter",
  "36&&Ribbon&&Super Carrot",
  "37&&Consumption&&Rumi Donut",
  "38&&Consumption&&Rumi Cake",
  "39&&Consumption&&Gold Carrot",
  "40&&Consumption&&Cocoa Bomb",
  "41&&Other&&???",
  "42&&Other&&Congratulations! Trophy",
  "43&&Other&&Exclaimation point",
  "44-46&&Other&&???",
  "47&&Ribbon&&Rainbow Magic&&Does not actually give rainbow magic",
  "48-57&&Other&&???",
  "58&&Other&&RBRB カード(1.99)",
  "59&&Other&&???",
  "60&&Erina&&1.8 DLC バニークローバー",
  "61&&Erina&&1.8 DLC ウィンドブレッシング",
  "62&&Erina&&1.8 DLC フェアリーフルート",
  "63&&Erina&&1.8 DLC バニーメモリーズ",
  "64&&Badge&&Health Plus",
  "65&&Badge&&Health Surge",
  "66&&Badge&&Mana Plus",
  "67&&Badge&&Mana Surge",
  "68&&Badge&&Crisis Boost",
  "69&&Badge&&Atk Grow",
  "70&&Badge&&Def Grow",
  "71&&Badge&&Atk Trade",
  "72&&Badge&&Def Trade",
  "73&&Badge&&Arm Strength",
  "74&&Badge&&Carrot Boost",
  "75&&Badge&&Weaken",
  "76&&Badge&&Self Defense",
  "77&&Badge&&Armored",
  "78&&Badge&&Lucky Seven",
  "79&&Badge&&Hex Cancel",
  "80&&Badge&&Pure Love",
  "81&&Badge&&Toxic Strike",
  "82&&Badge&&Frame Cancel",
  "83&&Badge&&Health Wager",
  "84&&Badge&&Mana Wager",
  "85&&Badge&&Stamina Plus",
  "86&&Badge&&Blessed",
  "87&&Badge&&Hitbox Down",
  "88&&Badge&&Cashback",
  "89&&Badge&&Survival",
  "90&&Badge&&Top Form",
  "91&&Badge&&Tough Skin",
  "92&&Badge&&Erina Badge",
  "93&&Badge&&Ribbon Badge",
  "94&&Badge&&Auto Trigger",
  "95&&Badge&&Lilith's Gift",
  "96-159&&Status&&Health Up",
  "160-223&&Status&&Attack Up",
  "224-287&&Status&&Mana Up",
  "288-351&&Status&&Regen Up",
  "352-415&&Status&&Pack Up"
];